### ISSUE TITLE
ATD: Workshop Team Meeting Agenda and Notes

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#100]
### Overview
This Issue will serve as the meeting agenda and notes for the Access the Data workshop team

**Comment by snooravi** [comment]
## 12.13.2021

**Comment by ExperimentsInHonesty** [comment]
## 2022-1-08 Meeting Agenda

### Prework to prep for meeting
- [ ] 



### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/open-community-survey/projects/1#column-15476398)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Sarah](https://github.com/hackforla/access-the-data/issues/assigned/snooravi)
       - [ ] [Malak](https://github.com/hackforla/access-the-data/issues/assigned/MalakH21)
       - [ ] [Shika](https://github.com/hackforla/access-the-data/issues/assigned/ShikaZzz)
       - [ ] [Mike](https://github.com/hackforla/access-the-data/issues/assigned/mcmorgan27)



### New Items
- [ ]
- [ ] Create new meeting Agenda
  - [ ] Carry over anything that did not get addressed in the last meeting to the new meeting Agenda

### FYIs
- 
### Notes from meeting

### Task Items

**Comment by snooravi** [comment]
## 2022-1-04 Meeting Agenda

### Prework to prep for meeting
- [ ] 


### Recurring items: 
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22feature%3A+workshops%22#column-15402664)
 - [x] Do we have any new videos to add to https://github.com/hackforla/access-the-data/issues/103
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Sarah](https://github.com/hackforla/access-the-data/issues/assigned/snooravi)
       - [ ] [Malak](https://github.com/hackforla/access-the-data/issues/assigned/MalakH21)
       - [ ] [Shika](https://github.com/hackforla/access-the-data/issues/assigned/ShikaZzz)
       - [ ] [Mike](https://github.com/hackforla/access-the-data/issues/assigned/mcmorgan27)



### New Items
- [ ] Malak is the only person who has not moved their files.  Please have her move her files at the next meeting she attends.  Her files are in this [folder](https://drive.google.com/drive/folders/1CQUy7hM7wVjOQepRG8A0srgIQRF4QBRM?usp=sharing) 
- [x] Briefly discuss if we already know of any videos that we will need to make for the 311 workshop? https://github.com/hackforla/access-the-data/issues/103 (after we update the issue with any we can think of now, we put this issue back in the icebox.)
- [x] Briefly discuss the status of resources we want to add to the resource aggregation (https://github.com/hackforla/access-the-data/issues/105)(after we update the issue with any we can think of now, we put this issue back in the icebox.)
- [ ] Create new meeting Agenda
  - [ ] Carry over anything that did not get addressed in the last meeting to the new meeting Agenda

### FYIs
- 
### Notes from meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
## 2022-01-19 Meeting Agenda

### Prework to prep for meeting
- [ ] 

### Recurring items: 
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22feature%3A+workshops%22#column-15402664)
 - [ ] Do we have any new videos to add to https://github.com/hackforla/access-the-data/issues/103
 - [x] Do we have any new resources to add to the resource aggregation (311Data Workshop Resource Aggregation #105 we update the issue with any we can think of now, we put this issue back in the icebox.)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Sarah](https://github.com/hackforla/access-the-data/issues/assigned/snooravi)
       - [ ] [Malak](https://github.com/hackforla/access-the-data/issues/assigned/MalakH21)
       - [ ] [Shika](https://github.com/hackforla/access-the-data/issues/assigned/ShikaZzz)
       - [ ] [Mike](https://github.com/hackforla/access-the-data/issues/assigned/mcmorgan27)

### New Items 
- [ ] Create new meeting Agenda
  - [ ] Carry over anything that did not get addressed in the last meeting to the new meeting Agenda
- [ ] Review issue #97 
- [ ] Review data scripts that mike worked on

### FYIs
- 
### Notes from meeting

### Task Items

**Comment by mxajPrice** [comment]
## 2022 March 21 - AtD Workshops Meeting

### AGENDA
_Timezones listed as PDT._
_Note: the Zoom room will close abruptly at the end-time of the meeting to accommodate another Hack for LA meeting._
- [ ] 17:00  _10 minutes_- Issues updates
- [ ] 17:00 _40 minutes_- working session

> Attendees:

> PMs
> - [ ] [Sarah Nooravi](https://github.com/hackforla/access-the-data/issues/assigned/snooravi)
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2)
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice)

> Data
> - [ ] [Malak Hmimy](https://github.com/hackforla/access-the-data/issues/assigned/malakh21)
> - [ ] [Mike Morgan](https://github.com/hackforla/access-the-data/issues/assigned/mcmorgan27)
> - [ ] [Stephanie Cho](https://github.com/hackforla/access-the-data/issues/assigned/scho-git)
> - [ ] [Serdar Celebi](https://github.com/hackforla/access-the-data/issues/assigned/Avangarde2225)
> - [ ] [Anupriya Jayakumar](https://github.com/hackforla/access-the-data/issues/assigned/priyakalyan)

> Portfolio Owner
> - [ ] [Bonnie Wolfe](https://github.com/hackforla/access-the-data/issues/assigned/ExperimentsInHonesty)

**Comment by mxajPrice** [comment]
## 2022 March 21 - AtD Workshops Meeting

### AGENDA
_Timezones listed as PDT._
_Note: the Zoom room will close abruptly at the end-time of the meeting to accommodate another Hack for LA meeting._
- [ ] 17:00  _10 minutes_- Issues updates
- [ ] 17:00 _40 minutes_- Recorded run-through of slides - @scho-git 

### NOTES

- In this meeting Stephanie and Malak worked on [Workshop 1: 311Data in Action](https://docs.google.com/presentation/d/1mlYV3ELIGxeoxvKBAjjukZ51uTbl6daB5hcAIp9arDI/edit?usp=sharing) slides

> Attendees:

> PMs
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2)
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice)

> Data
> - [ ] [Malak Hmimy](https://github.com/hackforla/access-the-data/issues/assigned/malakh21)
> - [ ] [Mike Morgan](https://github.com/hackforla/access-the-data/issues/assigned/mcmorgan27)
> - [ ] [Stephanie Cho](https://github.com/hackforla/access-the-data/issues/assigned/scho-git)
> - [ ] [Serdar Celebi](https://github.com/hackforla/access-the-data/issues/assigned/Avangarde2225)
> - [ ] [Anupriya Jayakumar](https://github.com/hackforla/access-the-data/issues/assigned/priyakalyan)

> Portfolio Owner
> - [ ] [Bonnie Wolfe](https://github.com/hackforla/access-the-data/issues/assigned/ExperimentsInHonesty)

**Comment by mxajPrice** [comment]
With workshops on hold until further notice, I am closing this issue.
