### ISSUE TITLE
PM To-Do

### ISSUE THREAD

**Issue by snooravi** [hackforla/access-the-data#104]
### Overview
Putting together a list of things to do before the new year.

### Action Items

- [ ] Split up the [workshop slides](https://github.com/hackforla/access-the-data/issues/97) issue into it's parts
- [ ] Write issue about next steps for [exploratory analysis](https://github.com/hackforla/access-the-data/issues/83) issue 
- [ ] Put together a proposal for Julien for next year's time commitment 
- [ ] Work through this issue https://github.com/hackforla/data-science/issues/26

### Comments

Completed
- [x] Understand the need for this issue and fill out with details: https://github.com/hackforla/access-the-data/issues/98
- [x] Review [SEIS Qualitative Survey Analysis](https://docs.google.com/document/d/1xlpyBClq6Py9K023REIijf3RHt7TLpH1zWW6759Oswk/edit#heading=h.fygqv5wam51l)--Final version [here](https://docs.google.com/document/d/13TVGgBeNxRKLfq64E1KdJ8RlkZiIFhp_xrj1pw-gmpI/edit#heading=h.fygqv5wam51l)
- [x] review #85 
- [x] add dependency on #105 
- [x] Find time to be interviewed by UX researcher about origin story to how the purpose and project was developed #106

**Comment by snooravi** [comment]
@ExperimentsInHonesty Mind reviewing this issue and LMK if I missed anything. Thanks!

**Comment by lrchang2** [comment]
@snooravi please tell us how many hours this will take

**Comment by snooravi** [comment]
@lrchang2 updated with the size. Thanks

**Comment by lrchang2** [comment]
@snooravi Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by snooravi** [comment]
@lrchang2 Can I get your help splitting up the slides using [this](https://docs.google.com/spreadsheets/d/1k8DvQ0wiiT3YJVliscCXOtXAiHx1yJDhPvjzYHZpOLQ/edit#gid=0) template.

**Comment by ExperimentsInHonesty** [comment]
update on 311 data pipeline https://github.com/hackforla/311-data/issues/1165

**Comment by lrchang2** [comment]
closing, this was sarah's personal issue and she is off the project now
