### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#140]
### Overview
We need to develop a project roadmap for Access the Data that includes workshop, website, design system, and branding/communication guide.

### Action Items

- [ ] Map out project deliverables for the next 6 months
- [ ] Consolidate and refine [list of milestones](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=144012752)
- [ ] Breakdown milestones into Action Items 
- [ ] Develop timeline of Action Items
- [ ] Create issues for all action items

### Next Steps

- Update one-sheet #1 
- Update milestone labels #95
