### ISSUE TITLE
Create Roadmap

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#142]
### Overview
We need to create a visual roadmap to communicate to the team what has been done and what is yet to be done.

### Action Items

- [ ] Audit the [milestones listed in GitHub](https://github.com/hackforla/access-the-data/milestones?direction=asc&sort=title&state=open) and the milestones on the [Competitive/Comparative Analysis](https://docs.google.com/spreadsheets/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=144012752)
- [ ] Create a draft "[ugly roadmap](https://docs.google.com/spreadsheets/d/1zRbcnpmtiQQQKReybQFOp4nE0Aa6KkLeAp4bxcncWVc/edit#gid=0)"
- [ ] If needed, redefine scope of workshops
- [ ] Finalize roadmap
- [ ] Update project [onesheet](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Access-the-Data-One-Sheet.pdf) and the main [AtD GitHub page](https://github.com/hackforla/access-the-data)

**Comment by mxajPrice** [comment]
We currently have a draft of the updated goals which needs to be finalized and approved by Bonnie.  Will discuss in today's PM meeting.
