### ISSUE TITLE
Familiarize self with project's historical work on personas [Phase 1_Website User Flows and Wireflows]

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/access-the-data#169]
**Overview**

Phase 1 focusses on familiarizing oneself with the project's historical work on personas

**Action Items**

- [ ] Collect resources from UX/UI leads and review 
- [ ] Review all databases related to ATD > GitHub, Google Drive, Figma, anything else.. 
- [ ] Collect Best Practices 
- [ ] Review Best Practices 
- [ ] Create simple Slide Deck with the primary information

**Comment by Aparna1Gopal** [comment]
https://github.com/hackforla/access-the-data/issues/145#issuecomment-1122678273

**Comment by Aparna1Gopal** [comment]
**Tasks**

- [ ] Collect resources from UX/UI leads and review 
- [ ] Review all databases related to ATD > GitHub, Google Drive, Figma, anything else.. 
- [ ] Collect Best Practices 
- [ ] Review Best Practices 
- [ ] Create simple Slide Deck with the primary information

**Comment by Aparna1Gopal** [comment]
Please refer to https://github.com/hackforla/access-the-data/issues/145 for progress updates

**Comment by Aparna1Gopal** [comment]
@lrchang2 This issue needs to be deleted. Thanks!
