### ISSUE TITLE
Community Activist Screener Survey Recruitment

### ISSUE THREAD

**Issue by bradyse** [hackforla/access-the-data#184]
### Dependencies

Recruitment/outreach of community advocate and expanding the database https://github.com/hackforla/access-the-data/issues/193

### Overview
We need to continue the recruitment for the Community Activist Persona screener survey so that we can interview users who are community activists.

### Action Items

- [x] Using [Initial Contacts Spreadsheet](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit#gid=0), email individuals who were formerly contacted via LinkedIn, as well as individuals who were initially contacted.
- [x] Expand Community Activist Survey Recruitment #193
- [x] Update  [Initial Contacts Spreadsheet](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit#gid=0) with new leads.
- [x] Request @ExperimentsInHonesty to at-channel individuals via Hack for LA: [Recruitment Message](https://github.com/hackforla/access-the-data/issues/184#issuecomment-1154417632).
- [x] Monitor ATD email account to ensure that all contact responses have received a follow-up email reply.
- [x] Create new issue for Create Interview Script for Community Activists #197
- [x] Investigate social media platforms to post [Recruitment Message](https://github.com/hackforla/access-the-data/issues/184#issuecomment-1154417632).

### Resources/Instructions

- [Email Template for Screener Survey](https://docs.google.com/document/d/1IXu9rG2X-5Jx01zxp6MuSpZwQzJ09HYMvgdQGA-2hXQ/edit)
- [Wiki- Research: Community Activist](https://github.com/hackforla/access-the-data/wiki/Research:-Community-Activist)
- [Issue #147: Persona 1 Recruitment Strategy](https://github.com/hackforla/access-the-data/issues/147) (closed issue originally made by Kim T.)
- [Initial Contacts Spreadsheet](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit#gid=0)

**Comment by bradyse** [comment]
### At-Channel Recruitment Message

📊 Access the Data team is looking for individuals to interview and connect with to learn more about accessibility to city data.

🏙 We'd love to learn more about people in our communities that are doing community work. This short survey will help us in finding community members to talk to and gain insights for building out an easy-to-navigate website of LA's open data resources.

✍🏿 The [Screener Survey](https://docs.google.com/forms/d/e/1FAIpQLSd-lHSN9DLLzvpCtm05zKGkbHRQ2LoIvbZjJ9ilOcgV0-Xeqg/viewform) takes only 2 minutes to complete and will be used solely for our research. Information from this screener will be used internally and anonymously. Thank you for your participation.

**Comment by bradyse** [comment]
### Email Template

Hi **(Contact Name)**,

I’m **(HfLA Name)**, a member of [Hack for LA’s](https://www.hackforla.org/#) [Access the Data](https://www.hackforla.org/projects/access-the-data.html) research team. Our goal with the Access the Data project is to help people make data-driven decisions that impact government policies by partnering with community activists and by providing free and open-source educational content about using city-wide data. We want to make sure that we design something that community activists in LA will actually find useful and actionable. 


With these project goals in mind, I’m reaching out to thank you for completing our survey and to ask you if you’d be willing to participate in an interview with me? I’d love to hear some more details about your experience as a community activist. If you’d like to participate in an interview, please let me know your availability to meet on Zoom for 30 minutes or so. My availability is flexible over the next few weeks, and I’d be happy to meet whenever you’re able to. 


Looking forward to hearing from you,

(insert email signature)
[Email Signature- Use Second One](https://docs.google.com/document/d/1DYj5weYdvgz_PqsnpLM-WFQdED5YyPXDkWKmgEuXvY0/edit)

**Comment by bradyse** [comment]
**2022.06.20 Update**

@joycekyang emailed several community activists from spreadsheet.
Created #193 to better target HfLA projects that are involved with Citizen Engagement.

**Comment by joycekyang** [comment]
I think this updated version is definitely more personable and do think it is helpful. (I think one thing that we could also add is something along the lines of "I noticed that you are apart of _____ project/organization" because it might help give the impression that what we are going to be talking about, relates to their work!

**Comment by bradyse** [comment]
@mmelovega @joycekyang @Aparna1Gopal @hannahsgr 

### Updates as of 2022-07-07:
- [X] Sent email to EmpowerLA using the [newly revised recruitment email message](https://docs.google.com/document/d/1IXu9rG2X-5Jx01zxp6MuSpZwQzJ09HYMvgdQGA-2hXQ/edit).
- [X] Sent email to I.L. (AJ's friend) to request completion of the survey and also copied recruitment email.
- [X] Updated [contact list spreadsheet](https://docs.google.com/spreadsheets/d/1lE-0M2Fc9Njf71aG9wrlE5gXhyWh_hV1AnXEtKnu558/edit?usp=sharing).
- [ ] Keep checking ATD gmail account to see if anyone responds.
- [ ] Create interview script. - _anyone interested in doing this in anticipation of interviewing AJ's friend?_

### Comments
- Still only one response to our screener survey (C.R. who was already interviewed--twice!).
- AJ mentioned that I.L. was interested in completing the survey and being interviewed. I.L. is traveling the last week of July, though.
- I noticed that the Data Expert persona team posted their screener survey on Twitter. Who has access to Twitter and can we get this set up somehow?
- If the EmpowerLA people don't monitor their email, perhaps they'll respond on social media. If they could retweet our recruitment message, that would be fabulous.
- Bonnie still seems to be too busy with the internship to @ channel our recruitment message, but if anyone has a chance to get her to do this, please redirect her to copy/paste [the message here](https://github.com/hackforla/access-the-data/issues/184#issuecomment-1154417632).

**Comment by mxajPrice** [comment]
@KC243 can reach out to contacts in NY.  @mmelovega to send Kevin the survey template.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

**Currently following this recruitment strategy from my end:** 

- [ ] Posting the Screener message on external Slack channels 

[Clarified from UX Lead (Mariana V) and this Community Activist Persona Lead (Sara B) via Slack. Can post on external slack channels. Research participants can be from Los Angeles, United States and/or International. Due to this non-specificity, and/all Slack channels can be targeted) 

- [ ] Contacting a friend who works is social work for a non-profit to see they are willing to be interviewed

**Comment by bradyse** [comment]
- Received reply from an email that Kim sent back in April.
- Sent response and link to screener survey to Claire.
- Thank you @Aparna1Gopal for monitoring the Gmail account.

**Comment by Aparna1Gopal** [comment]
**Notes** 
**Currently following this recruitment strategy from my end:**

https://github.com/hackforla/access-the-data/issues/184#issuecomment-1179501393

Based on the above message, following are the updates: 

Have contacted the friend, they donot wish to be interviewed. Need to look at other resources/networks for recruiting and outreach.  

Posting the Screener message on external Slack channels

- [ ] UX Rescue
- [ ] Hexagon UX 
- [ ]

**Comment by Aparna1Gopal** [comment]
**Notes:** 

- Outreach to prospective research participant at Active San Gabriel Valley (ActiveSGV) https://www.activesgv.org/about#mission via email. 

- Used the following email template: 

Subject: 📊 Hack for LA wants to help community activists access the data 📊

Email template recorded here: Under Screener Survey Recruitment Message (Sent on August 15, 2022) 
https://docs.google.com/document/d/1IXu9rG2X-5Jx01zxp6MuSpZwQzJ09HYMvgdQGA-2hXQ/edit

**Comment by Aparna1Gopal** [comment]
**Notes**

Added Dependencies https://github.com/hackforla/access-the-data/issues/193 to this issue, since both issues are inter-connected and overlap at this point. 

This issue is complete and is also currently being tracked in https://github.com/hackforla/access-the-data/issues/193

**Comment by Aparna1Gopal** [comment]
@lrchang2 @mxajPrice @bkong 

- **This issue can be closed** 

- This issue is complete and is also currently being tracked in https://github.com/hackforla/access-the-data/issues/193

CC: @mmelovega @hannahsgr @Aparna1Gopal

**Comment by Aparna1Gopal** [comment]
### Notes: 

**Based on meeting with PM Lucy C on October 13, 2022 this is being closed.**

- The project is currently pivoting in a new direction based on the current requirements of Access the Data. This includes ATD’s Website redesign based on CKAN incorporation and pivoting from the prior education modules model

- The personas (data expert and community activist) were developed during the education modules iteration of the project. The idea of creating a database of a research participant pool of data experts and community activists were also formulated during this stage of the project. 

- UX Researchers (prior & current) working on this issue have utilized multiple methods for outreach and recruiting research participants: including internal HfLA Slack, external Slack groups, Twitter, Email, cold calling etc. with links to Calendly for interview sign-up

- UX Researchers working on this issue have also expanded the database of potential community advocates/data experts over the course of 6+ months. 

- With the current restructuring of the team and the vision for the ATD website moving forward, LinkedIn poll is being used as a new strategy for participant recruitment. 

- This will also be used as a strategy to conduct new generative research to identify other persona types who will be potential users of ATD website & CKAN. 

- The important details from this issue will be transferred to ATD’s Wiki by the PMs.
