### ISSUE TITLE
2023 Weekly PM Meeting Agenda

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/access-the-data#258]
### Overview
This issue tracks meeting agenda and summary for the Access the Data PM meetings.

### Agenda Quick-Links
[22 August 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1676651806)
[15 August 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1670101907)
[8 August 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1660976813)
[1 August 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1650423615)
[25 July 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1640660158)
[11 July 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1631278297)
[3 July 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1619011277)
[27 June 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1608354448)
[20 June 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1597488513)
[13 June 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1588019116)
[31 May 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1570580714)
[22 May 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1557826897)
[1 May 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1522439292)
[24 April 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1516996131)
[17 April 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1509486736)
[4 April 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1496611760)
[28 March 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1487542639)
[21 March 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477303025)
[14 March 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477302509)
[28 February 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477302294)
[21 February 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477302015)
[14 February 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477301669)
[7 February 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477301159)
[31 January 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477300763)
[24 January 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477300560)
[17 January 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477300373)
[10 January 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477300119)
[03 January 2023](https://github.com/hackforla/access-the-data/issues/258#issuecomment-1477299741)

### Resources/Instructions
Previous agendas can be found on #70

**Comment by mxajPrice** [comment]
## 2023 January 03 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [x] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [x] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - Review current roster and make sure it is up-to-date
- [x] 14:05 _5 min_ - Clean up Kanban where needed
- [x] 14:10 _10 min_ - Review previous[ retrospective](https://jamboard.google.com/d/12Pg4Z-ve0gS8lGpjmv_cBxiuDeXRSFfkp0Lq8a3BCDo/edit?usp=sharing) and team meeting [notes](https://github.com/hackforla/access-the-data/issues/63#issuecomment-1335968193)
- [x] 14:20 _10 min_ - Start process of scheduling recurring development meetings
- [ ] 14:30 _10 min_ -  Schedule meeting with designers and developers to talk about next steps in integration
- [ ] 14:40 _10 min_ - Create next team meeting agenda #63 



#### FYIs


#### Notes from meeting
- cleaned up roster - need to offboard hannah and bailey in #240 
- went through all the KanBan boards. the project has pivoted to focusing team effort on developing the website
- reviewed the notes from the previous retrospective and based on feedback: 
    - added a new issue #241 for PMs
    - made weekly meeting for developers on Thursdays at 5:30PM PT - PMs will be joining for the first meeting
    - reached out to team for design/development integration via slack to set up meeting



#### Task Items
- Start planning posting for PM on next PM meeting
- talk to Aparna and cleaning up and scoping down #192 and #191

**Comment by mxajPrice** [comment]
## 2023 January 10 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 14:00 _5 min_ - Prep tomorrow team meeting agenda #63 
- [ ] 14:05 _5 min_ - Create posting for PM
- [ ] 14:10 _10 min_ - Review #191 & #192 and prepare to scale down with Aparna
- [ ] 14:20 _10 min_ - 
- [ ] 14:30 _10 min_ -  
- [ ] 14:40 _10 min_ - 



#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 January 17 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 14:00 _5 min_ - Review [research wiki](https://github.com/hackforla/access-the-data/wiki/ATD-Research:-Unmoderated-Usability-Testing-(Competitive-analysis-of-CKAN-websites)) and approve closing of #191 
- [x] 14:05 _5 min_ - Review #236 and discuss/approve #1 or #2 "Get Involved" vs. "Join us".  Perhaps make a poll on Slack.
- [ ] 14:10 _10 min_ - 
- [ ] 14:20 _10 min_ - 
- [ ] 14:30 _10 min_ -  
- [ ] 14:40 _10 min_ - 



#### FYIs


#### Notes from meeting
- In team meeting, Aparna pointed out that the "research overview" link at the bottom of the wiki [ref](https://github.com/hackforla/access-the-data/wiki/ATD-Research:-Unmoderated-Usability-Testing-(Competitive-analysis-of-CKAN-websites)) is incorrect.  This was copied and pasted from the persona wiki pages.  We think the correct link should be [this](https://github.com/hackforla/access-the-data/wiki/Research-Guides).

#### Task Items

**Comment by mxajPrice** [comment]
## 2023 January 24 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [x] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [x] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - #33 
- [x] 14:05 _5 min_ - #94
- [x] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [x] 14:15 _10 min_ - Prep #63 
- [x] 14:25 _10 min_ -  Prep #155 
- [x] 14:35 _10 min_ - Updates on current open issues
   - #242 
   - #190 
   - #243 
- [x] 14:45 _5 min_ - Create issue to offboard Elaine; create posting for new PM


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 January 31 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - #33 
- [x] 14:05 _5 min_ - #94
- [x] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [x] 14:15 _10 min_ - Prep #63 
- [ ] 14:25 _10 min_ - Review Aparna's [research plan](https://docs.google.com/document/d/1paDMwGXDM73MpdSDu7iZH7ZCYySel1WtVZjCpV-zZDI/edit#) RE: #192 
- [x] 14:35 _5 min_ - Create issue for Leslie to develop copy for Volunteering page
- [ ] 14:40 _5 min_ - Begin #243 


#### FYIs
- In the last Team Meeting, Aparna said she will be sending us her research plan for our review over the weekend.
- There are some updates from the 27 January PM CoP:
   - Bonnie has asked that all “agenda” issues be marked with an agenda label.  This is already done for us.
   - Bonnie gave us a heads up that HfLA is splitting off from Code for America and estimates that in six months it will be the child of a new parent non-profit that she is putting together.  One of the major implications here is that we will need to shift our AtD Google account to another Google account.
   - I requested that we start polling the PMs once a month to get some general info on where everyone is at.  As a quick-and-dirty start to this Bonnie put out a questionnaire on Slack but it is still being developed.  I will answer on our behalf this time.
   - Our one-sheet was last updated six months ago.  I updated it with our [current six-month roadmap](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit#heading=h.3jvxuu9bqufe) (which I also posted on the Kanban) and will submit it to VRMS for update.

#### Notes from meeting


#### Task Items
- [ ] PMs to continue looking over Aparna's research plan

**Comment by mxajPrice** [comment]
## 2023 February 7 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - #33 
- [ ] 14:05 _5 min_ - #94
- [ ] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 14:15 _10 min_ - Prep #63 
- [ ] 14:25 _5 min_ - Begin #243 


#### FYIs


#### Notes from meeting
- We decided that there were few enough items that we could discuss asynchronously. 

#### Task Items

**Comment by mxajPrice** [comment]
## 2023 February 14 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [x] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [x] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - #33 
- [x] 14:05 _5 min_ - #94
- [x] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [x] 14:15 _10 min_ - Prep #63 
- [ ] 14:25 _5 min_ - Continue #243 


#### FYIs


#### Notes from meeting


#### Task Items

- new section was added to https://www.hackforla.org/projects/access-the-data and needs to be updated. comment put in #162 about it

**Comment by mxajPrice** [comment]
## 2023 February 21 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [x] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [x] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - #33 
- [x] 14:05 _5 min_ - #94
- [x] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [x] 14:15 _10 min_ - Prep #63 
- [ ] 14:25 _5 min_ - Continue #243 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 February 28 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - #33 
- [x] 14:05 _5 min_ - #94
- [x] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 14:15 _10 min_ - Prep #63 
- [ ] 14:25 _5 min_ - Continue #243 


#### FYIs
- PM CoP meeting notes:
   - @mxajPrice to create demo on creating shared calendars for next meeting.  (How did I get the calendar link like I have in the link in "Documents" on the kanban?)

#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 March <s>07</s> 14 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [x] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [x] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 14:00 _5 min_ - Touch base
- [x] 14:05 _5 min_ - #33 & #94
- [x] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [x] 14:15 _10 min_ - #254
- [x] 14:25 _10 min_ - Prep #63 
- [x] 14:35 _5 min_ - Continue #243 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 March 21 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 14:00 _5 min_ - Touch base
- [ ] 14:05 _5 min_ - #33 & #94
- [ ] 14:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 14:15 _10 min_ - [Update project meeting times](https://hackforla.slack.com/archives/C010LNXH2JY/p1678233078914869)
- [ ] 14:25 _10 min_ - Prep #63 
- [ ] 14:35 _5 min_ - 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 March 21 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
> - [ ]  Cathy Cai

### AGENDA
_Timezones listed as PDT._

- [ ] 14:00 _5 min_ - Touch base
- [ ] 14:05 _30 min_ - #257 
- [ ] 14:35 _10 min_ - [Update project meeting times](https://hackforla.slack.com/archives/C010LNXH2JY/p1678233078914869)
- [ ] 14:45 _5 min_ - Prep #63 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 April 4 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2) _CDT_
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
> - [ ]  Cathy Cai

### AGENDA
_Timezones listed as PDT._

- [ ] 14:00 _5 min_ - Touch base
- [ ] 14:05 _40 min_ - #257 
- [ ] 14:45 _5 min_ Prep #259 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 April 17 - PM Meeting

> ##### _Prework_

> ##### Meeting Attendance
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
> - [ ] [Cathy Cai](https://github.com/hackforla/access-the-data/issues/assigned/cathyyyyyy) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _5 min_ - #33 & #94
- [ ] 17:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:15 _10 min_ - Prep #259
- [ ] 17:25 _10 min_ - Create issue to offboard Lucy
- [ ] 17:35 _5 min_ - 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 April 24 - PM Meeting

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Cathy Cai](https://github.com/hackforla/access-the-data/issues/assigned/cathyyyyyyyy) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _5 min_ - Go through all In Progress issues and make sure:
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:15 _10 min_ - Prep #259
- [ ] 17:25 _10 min_ - 
- [ ] 17:35 _5 min_ - 


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 March 1 - PM Meeting

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Cathy Cai](https://github.com/hackforla/access-the-data/issues/assigned/cathyyyyyyyy) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _5 min_ - Go through all In Progress issues and make sure:
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:10 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:15 _10 min_ - Prep #259
- [ ] 17:25 _10 min_ - 
- [ ] 17:35 _5 min_ - 


#### FYIs
- Opened issue #4566 with website team to update our team info on the HfLA site.

#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 May 22 - PM Checklist


- [ ] Go through all In Progress issues and make sure:
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- Prep #259
- hackforla/website#4566
- [PM issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Amxajprice)



#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 May 31 - PM Checklist


- [ ] Go through all In Progress issues and make sure:
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] Prep #259
- [ ] hackforla/website#4566
- [ ] [PM issues](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Amxajprice)



#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 June 20 - PM Meeting

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _15 min_ - Complete #283 
- [ ] 17:20 _10 min_ - Weekly PM duties
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:30 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:35 _10 min_ - Prep #259
- [ ] 17:45 _5 min_ - AOB


#### FYIs
- Opened hackforla/website#4818 with website team to update our team info on the HfLA site.
- Need to start [planning S2 One-sheet](https://github.com/hackforla/access-the-data/issues/new?assignees=&labels=documentation%2C+feature%3A+administrative%2C+role%3A+product+management%2C+role%3A+project+management%2C+size%3A+5+pts&projects=&template=update-project-goals---one-sheet.md&title=Update+AtD+Semester+Goals)

#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 June 27 - PM Meeting

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _15 min_ - Complete #283 
- [ ] 17:20 _10 min_ - Weekly PM duties
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:30 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:35 _10 min_ - Prep #259
- [ ] 17:45 _5 min_ - AOB


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 July 03 - PM Meeting

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _15 min_ - Complete #283 
- [ ] 17:20 _10 min_ - Weekly PM duties
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:30 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:35 _10 min_ - Prep #259
- [ ] 17:45 _5 min_ - AOB


#### FYIs


#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
https://github.com/

## 2023 July 11 - PM Meeting

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base / Announcements
   - Officially HfLA under Civic Tech Structure
   - No website and no donation system yet
- [ ] 17:05 _5 min_ - Updates on domain knowledge
- [ ] 17:15 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:20 _10 min_ - Weekly PM duties
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:30 _10 min_ - Prep #259
- [ ] 17:45 _5 min_ - AOB


#### FYIs
- hackforla/website/issues/4939 was created to update team members +Jason -Leslie -Bonnie on the HfLA site; hopefully the simplification will assure it gets done more quickly
- hackforla/website/issues/4818 is still open to update our technologies [HfLA AtD page](https://www.hackforla.org/projects/access-the-data).

#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 July 18 - PM Meeting
_[Back to Top](#)_

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _5 min_ - Review [ice box](https://github.com/hackforla/access-the-data/projects/1#column-12519284) and see if dependencies are still open or not
- [ ] 17:10 _10 min_ - Weekly PM duties
   - There is a feature, role, and size label
   - There is an update from the assignee from less than a week ago
      - If there is not, leave a comment on the issue asking for updates and mark it with a "To Update!" label
- [ ] 17:20 _10 min_ - Prep #259
- [ ] 17:30 _20 min_ - Run-through of meeting and what people are working on



#### FYIs
- hackforla/website/issues/4939 was created to update team members +Jason -Leslie -Bonnie on the HfLA site; hopefully the simplification will assure it gets done more quickly
- hackforla/website/issues/4818 is still open to update our technologies [HfLA AtD page](https://www.hackforla.org/projects/access-the-data).

#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
## 2023 July 25 - PM Meeting - CANCELLED

**Comment by mxajPrice** [comment]
## 2023 August 1 - PM Meeting
_[Back to Top](#)_

> Prework:
>    - #287

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _10 min_ - Review this [Software Development Lifecycle](https://www.coursera.org/articles/software-development-life-cycle) and determine where we are
- [ ] 17:15 _10 min_ Review current [one sheet](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit) and [project charter](https://docs.google.com/document/d/1hAxvBz3edPBLRFM23r7GSfX8GR11V6yJqyp7kieFczY/edit?resourcekey=0-MYHK7mTS8WoWNJJCfDcwQw) and discuss what needs to happen in the next six months
- [ ] 17:25 _15 min_ Make updates to the project charter and one sheet
   - Submit [one sheet updates](https://github.com/hackforla/access-the-data/issues/new?assignees=&labels=documentation%2C+feature%3A+administrative%2C+role%3A+product+management%2C+role%3A+project+management%2C+size%3A+5+pts&projects=&template=update-project-goals---one-sheet.md&title=Update+AtD+Semester+Goals)
   - Add a discussion of these updates to tomorrow's agenda
- [ ] 17:40 _10 min_ - Prep #259



#### FYIs
- hackforla/website/issues/4939 was created to update team members +Jason -Leslie -Bonnie on the HfLA site; hopefully the simplification will assure it gets done more quickly
- hackforla/website/issues/4818 is still open to update our technologies [HfLA AtD page](https://www.hackforla.org/projects/access-the-data).

#### Notes from meeting


#### Task Items

**Comment by merlinsmagic** [comment]
## 2023 August 8 - PM Meeting
_[Back to Top](#)_

> Prework:
>    - #287

##### Meeting Attendance
- [x] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [x] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [x] 17:00 _5 min_ - Touch base
- [x] 17:05 _10 min_ - Review this [Software Development Lifecycle](https://www.coursera.org/articles/software-development-life-cycle) and determine where we are
- [x] 17:15 _10 min_ Review current [one sheet](https://docs.google.com/document/d/17yzHv1Jx5Vf_QAHtgBZ0slU3no9BXneEB8GJscyKlpE/edit) and [project charter](https://docs.google.com/document/d/1hAxvBz3edPBLRFM23r7GSfX8GR11V6yJqyp7kieFczY/edit?resourcekey=0-MYHK7mTS8WoWNJJCfDcwQw) and discuss what needs to happen in the next six months
- [x] 17:25 _15 min_ Make updates to the project charter and one sheet
   - Submit [one sheet updates](https://github.com/hackforla/access-the-data/issues/new?assignees=&labels=documentation%2C+feature%3A+administrative%2C+role%3A+product+management%2C+role%3A+project+management%2C+size%3A+5+pts&projects=&template=update-project-goals---one-sheet.md&title=Update+AtD+Semester+Goals)
   - Add a discussion of these updates to tomorrow's agenda
- [ ] 17:40 _10 min_ - Prep #259



#### FYIs
- hackforla/website/issues/4939 was created to update team members +Jason -Leslie -Bonnie on the HfLA site; hopefully the simplification will assure it gets done more quickly
- hackforla/website/issues/4818 is still open to update our technologies [HfLA AtD page](https://www.hackforla.org/projects/access-the-data).

#### Notes from meeting


#### Task Items

**Comment by merlinsmagic** [comment]
## 2023 August 15 - PM Meeting
_[Back to Top](#)_

> Prework:
>    - #287

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _15 min_ Make updates to the project charter and one sheet based on conversation with Aparna
   - Submit [one sheet updates](https://github.com/hackforla/access-the-data/issues/new?assignees=&labels=documentation%2C+feature%3A+administrative%2C+role%3A+product+management%2C+role%3A+project+management%2C+size%3A+5+pts&projects=&template=update-project-goals---one-sheet.md&title=Update+AtD+Semester+Goals)
   - Add a discussion of these updates to tomorrow's agenda
- [ ] 17:20 _10 min_ - Prep #259
- [ ] 17:30 _20 min_ - Review [current PM issues](https://github.com/hackforla/access-the-data/projects/1)



#### FYIs
- hackforla/website/issues/4818 is still open to update our technologies [HfLA AtD page](https://www.hackforla.org/projects/access-the-data).

#### Notes from meeting


#### Task Items

**Comment by merlinsmagic** [comment]
## 2023 August 22 - PM Meeting
_[Back to Top](#)_

> Prework:
>    - #287

##### Meeting Attendance
- [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice) _PDT_
- [ ] [Jason Yung](https://github.com/hackforla/access-the-data/issues/assigned/merlinsmagic) _PDT_

### AGENDA
_Timezones listed as PDT._

- [ ] 17:00 _5 min_ - Touch base
- [ ] 17:05 _10 min_ Make updates to the project charter and one sheet based on conversation with Team
   - Submit [one sheet updates](https://github.com/hackforla/access-the-data/issues/new?assignees=&labels=documentation%2C+feature%3A+administrative%2C+role%3A+product+management%2C+role%3A+project+management%2C+size%3A+5+pts&projects=&template=update-project-goals---one-sheet.md&title=Update+AtD+Semester+Goals)
   - Add a discussion of these updates to tomorrow's agenda
- [ ] 17:15 _10 min_ - Prep #259
- [ ] 17:25 _20 min_ - Review [current PM issues](https://github.com/hackforla/access-the-data/projects/1)
- [ ] 17:45 _5 minutes_ - Follow up https://github.com/hackforla/website/issues/5127



#### FYIs
- hackforla/website/issues/4818 is still open to update our technologies [HfLA AtD page](https://www.hackforla.org/projects/access-the-data).

#### Notes from meeting


#### Task Items

**Comment by mxajPrice** [comment]
Closing this issue as the MVP is concluded.
