### ISSUE TITLE
Low/Mid Fidelity Website Wireframes 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#37]
### Dependencies 
~#36~ 
~#77~ 
~#102~

### Overview
We need to develop and test low fidelity wireframe prototypes of the website to know how the website structure will be.

Low Fidelity = sketches, grey-scale
Mid Fidelity = clickable prototype, ~color~, a version of content

### Action Items

- [x] mobile version
   - [x] Use information architecture #36  to prototype low-fi web pages
      - [x] develop components first:
           - [x] nav bar
           - [x] footer
           - [x] buttons
   - [x] Do iterative rapid user testing on low-fi wireframe to confirm the functionality of the website structure #88 
   - [x] apply edits and move on to high-fi wireframes #41 
- [x] develop desktop version based on mobile version
   - [ ] develop components first:
      - [ ] nav bar
      - [ ] footer
      - [ ]  buttons

**Comment by melissamurphy** [comment]
From [Card Sort for website](https://github.com/hackforla/access-the-data/issues/77) at today's website team meeting
<img width="1372" alt="Group Card Sort AtD 100821" src="https://user-images.githubusercontent.com/54216219/136532052-2b4a6732-abd6-4cd6-9630-1c33dcdecf29.png">

**Comment by melissamurphy** [comment]
[Sitemap in Figma](https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A7) based on above Card Sort

<img width="647" alt="Screen Shot 2021-10-08 at 2 21 09 AM" src="https://user-images.githubusercontent.com/54216219/136533666-1effc163-30e5-45f5-8157-e7da61b4cb84.png">




@henrywang7 @mathhomework @miguel-hugo @lrchang2 @abryant35

**Comment by lrchang2** [comment]
mid fi version is done and can be seen [here](https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A13)  and usability testing #88 has be finished. closing issue

**Comment by KaylenaNguyen** [comment]
reopening issue to add desktop version of mid-fi

**Comment by lrchang2** [comment]
@KaylenaNguyen
Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.

**Comment by KaylenaNguyen** [comment]
Progress: About finished with the Hi-Fi wireframes. All that's left to do is edit some font sizes. Miguel will also look it over and edit what needs to be done.
Blockers: Had some difficulties with colors but Joanna helped me out with that. 
Availability: A couple hours.
ETA: If not tonight, tomorrow (12/02).
Pictures: https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16

**Comment by lrchang2** [comment]
@KaylenaNguyen 
Please add update using this template

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either:

ask for help at your next meeting
put a "Status: Help Wanted" label on your issue and pull request
put up a request for assistance on the #access-the-data channel.

**Comment by ExperimentsInHonesty** [comment]
Hack for LA should not appear in the partners section. it should be at the bottom of the footer.  See the footer for the 100automations.org site https://100automations.org/  it doesen't have to look exactly like that, but lets talk about your proposal.

**Comment by ExperimentsInHonesty** [comment]
Make Government Data your Superpower is not exactly right.  It's really Using Government data.  So maybe try some other options to make it clearer.  Off the top of my head... not saying to use these words but let's just make sure it's clear.
Make using government data your super power
Using Government Data can be your super power
Make accessing Government Data your super power

**Comment by ExperimentsInHonesty** [comment]
Lets use the color city logohttps://www.pngfind.com/mpng/hJbwwmR_city-of-los-angeles-crest-transparent-city-of/in the partners section

**Comment by KaylenaNguyen** [comment]
Progress: I need to update and use the components. Add images as well as fix font sizes. Also, everything Bonnie mentioned.
Blockers: No blockers or errors encountered. 
Availability: I'll have about 4 hours this week to work on this.
ETA: I am hoping by the end of this week.
Pictures: https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16

**Comment by KaylenaNguyen** [comment]
Progress: Made changes based on what Bonnie mentioned. Still need to add images and the Hack For LA logo in the footer.
Blockers: No blockers or errors.
Availability: I'll have a few hours this week. If there are major changes or updates, I'll do as much as I can. However, if anyone can help if I can't get it done by this weekend, that would be great.
ETA: Hopefully, we can go over what images we should use and where. I think that's the biggest thing right now.
Pictures: https://www.figma.com/file/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2%3A16

**Comment by lrchang2** [comment]
new website that needs to be applied to wireframes can be found [here](https://github.com/hackforla/access-the-data/issues/87#issuecomment-999108082).

**Comment by lrchang2** [comment]
closing because focus has shifted to high fi

**Comment by lrchang2** [comment]
closing because focus has shifted to high fi
