### ISSUE TITLE
ATD: UX/UI Meeting Agenda and Summary

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#64]
### Overview
This issue tracks the agenda for the Access the Data team meeting.

Website meetings are on Thursdays at 4-5PM PST

### Weekly Agenda
[September 16, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-918619036)
[September 23, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-921522720)
[September 30, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-931743212)
[October 07, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-937375696)
[October 14, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-948150614)
[October 21, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-948151228)
[October 28, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-953431959)
[November 04, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-960370529)
[November 11, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-960376661)
[November 18, 2021](https://github.com/hackforla/access-the-data/issues/64#issuecomment-973065558)

**Comment by lrchang2** [comment]
Agenda and Summary for Week of September 16 2021

Agenda: 



Summary:

**Comment by lrchang2** [comment]
September 22 2021 
,
**Participants:**


**Things to discuss:**

- Review research questions for plan PMs have ideated on  #62 
- review survey questions and places to send out survey #68 
- review interview questions for open ended interview #58 
- review competitive website usability questions, structure of interview and recruitment plan #69 

**Things discussed:**



**Actions to take:**

**Comment by abryant35** [comment]
September 30 2021
,
Participants:
Alyssa, Lucy, Melissa, Joanna

Things to discuss:


Things discussed:


Actions to take:

**Comment by lrchang2** [comment]
October 14, 2021

Things discussed:
working meeting

**Comment by lrchang2** [comment]
October 21 2021

Participants:


Things to discuss:

- define website copy audience and direction
- talk about research recruitment issues/blockers
- breakout rooms to work on research, copy, or wireframes 

Things discussed:

Actions to take:

**Comment by abryant35** [comment]
November 03, 2021

Participants:

Things to discuss:

- Website copy
- Go over professional experience on 11/10



Actions to take:

**Comment by lrchang2** [comment]
November 11, 2021

Participants:

Things to discuss:

- professional development for ux/ui team
- go over 
   - resume
   - linkedin
   - portfolio

Actions to take:

**Comment by lrchang2** [comment]
November 18, 2021

Things to Discuss: 
- usability testing results 
- content framing 
- find new meeting time for after thanksgiving 
- assign issues

**Comment by lrchang2** [comment]
December 2, 2021

Attendees: 

Things to Discuss:
- roadmap for developers - what can be worked on first (components/pages) 

Things Discussed:

Actions to Take:

**Comment by lrchang2** [comment]
## [insert date] Meeting Agenda

### Prework to prep for meeting
- [ ] [Audit](https://github.com/hackforla/access-the-data/issues/33)
- [ ] Review the prioritized backlog and clear any issues possible.
- [ ] https://github.com/hackforla/access-the-data/issues/94

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/open-community-survey/projects/1#column-15476398)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Designer
       - [ ] [Miguel](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Amiguel-hugo)
       - [ ] [Joanna](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Ajoanna-pham)
       - [ ] [Melissa](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Amelissamurphy)
       - [ ] [Ashley](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Aashleyxz)
       - [ ] [Tracy](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Atracyluu)
       - [ ] [Kaylena](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=assignee%3Akaylenanguyen)


### New Items

### FYIs

**Comment by lrchang2** [comment]
## 2022-01-27 Meeting Agenda

### Prework to prep for meeting
- [ ] Create new meeting Agenda
   - [ ] Carry over anything that did not get addressed in the last meeting to the new meeting Agenda

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/access-the-data/projects/1?card_filter_query=label%3A%22feature%3A+workshops%22#column-15402664)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Designer
       - [ ] [Sarah](https://github.com/hackforla/access-the-data/issues/assigned/snooravi)
       - [ ] [Malak](https://github.com/hackforla/access-the-data/issues/assigned/MalakH21)
       - [ ] [Shika](https://github.com/hackforla/access-the-data/issues/assigned/ShikaZzz) 
       - [ ] [Mike](https://github.com/hackforla/access-the-data/issues/assigned/mcmorgan27)

### New Items 

### FYIs
- 
### Notes from meeting

-  removed Malak from #97 in the icebox and added a dependency to the issue she is working on.
- Mike is not currently assigned to any issues
- Uploaded mikes repo access-the-data-workshop-311-analysis
- removed Malak from an issue #97 and put in icbox with a dependency of #109
- spent some time creating two new wiki pages with the intent of sorting out the content from the resources document into content for the team and content for workshop participants 
  - https://github.com/hackforla/access-the-data/issues/105
  - https://github.com/hackforla/access-the-data/wiki/Workshop-Resources-for-Internal-Team
  - https://github.com/hackforla/access-the-data/wiki/Workshop-Resources-for-Internal-Team

### Task Items
- [ ] [Shika](https://github.com/hackforla/access-the-data/issues/assigned/ShikaZzz) - Confirm with Sarah that she is off the team, and offboard her

### Items for next weeks agenda

**Comment by lrchang2** [comment]
https://github.com/hackforla/access-the-data/issues/56 - still being worked on?

**Comment by lrchang2** [comment]
## 2022-01-27 Meeting Agenda

### Prework to prep for meeting
- [x] Create new meeting Agenda
   - [x] Carry over anything that did not get addressed in the last meeting to the new meeting Agenda

### Recurring items: 
 - [x] review any issues that are in the [new issue approval column](https://github.com/hackforla/access-the-data/projects/1#column-15402664)
 - [x] review goals/roadmap of project
 - [ ] Accountability and Support Check.
    - [ ] Review assignments and capacity for each Designer
       - [x] [Ashley](https://github.com/hackforla/access-the-data/issues/assigned/ashleyxz)
       - [x] [Kaylena](https://github.com/hackforla/access-the-data/issues/assigned/KaylenaNguyen) 
       - [x] [Archana](https://github.com/hackforla/access-the-data/issues/assigned/Archana-M)
       - [x] [Katelyn](https://github.com/hackforla/access-the-data/issues/assigned/katelyntn)
       - [ ] [Clarizza](https://github.com/hackforla/access-the-data/issues/assigned/delacrem)
       - [ ] Hannah

### New Items 

- [x] put skills wanting to develop on roster 
- [x] go through how to turn on slack notifications 
- [x] stakeholder presentation interest 
- [ ] usability test with new designers #102 

### FYIs

- set expectation to share screen to share with group about work update 
- onboarding will include transition from bootcamp to work 

### Notes from meeting

- design system components:
   -  button
   -  header and footer-hover for subpages 
- placeholder text for waitlist box and contact form 
- darker color for hover of buttons isnt in the color palette 
- feedback on button states

---

- kaylena provided comparison of bigger vs smaller buttons applied to the prototype so we can make a decision on the height of the button 
   - team voted, results were:  bigger  button (67%), smaller button (33%) 
   - comments were: 
      - bigger button seems to be more proportional to images and headings  
      - bigger button calls attention to it
      - [prototype that fills the whole screen ](https://www.figma.com/proto/nS5IqnutUT2FuPwwJObHaY/Access-the-Data-Main-Figma?node-id=2292%3A5665&scaling=scale-down&page-id=2%3A18&starting-point-node-id=2292%3A5665)
          - carousel should be "above the fold" 
 - favicon review from 
    - just the D 
    - check the contrast (able plugin) 
 - colors for logo 
    - solid color 




### Task Items

- [ ] Archana will make the bigger "carousel button" into the primary button for the design system
- [ ] competitive analysis of button types and sizes
- [ ] research says "missing the call to action" -signing up for workshops 
- [ ] Kaylena will update prototype with bigger button
- [ ] 

### Items for next weeks agenda

**Comment by mxajPrice** [comment]
## 2022 March 17 - UX/UI Working Session

### AGENDA
_Timezones listed as PDT._
- [ ] 16:00 _10 minutes_- Welcome New UX/UI teammates - @KaylenaNguyen 
- [ ] 16:10 _40 minutes_- Work on website design

Notes:

- Archana and Kaylena shared updates on the carousel

> Attendees:

> UI/UX Design
> - [ ] [Joanna Pham](https://github.com/hackforla/access-the-data/issues/assigned/joanna-pham) - Lead
> - [ ] [Kaylena Nguyen](https://github.com/hackforla/access-the-data/issues/assigned/KaylenaNguyen) - Lead
> - [ ] [Archana Mudiam](https://github.com/hackforla/access-the-data/issues/assigned/Archana-M)
> - [ ] [Katelyn Nguyen](https://github.com/hackforla/access-the-data/issues/assigned/katelyntn)
> - [ ] [Clarizza Mendoza](https://github.com/hackforla/access-the-data/issues/assigned/delacrem)
> - [ ] [Ogbonnia Eloka](https://github.com/hackforla/access-the-data/issues/assigned/eloks7)

> UX Research
> - [ ] [Melissa Murphy](https://github.com/hackforla/access-the-data/issues/assigned/melissamurphy)
> - [ ] [Xinyue (Ashley) Zuo](https://github.com/hackforla/access-the-data/issues/assigned/ashleyxz)
> - [ ] [Hannah Sangra](https://github.com/hackforla/access-the-data/issues/assigned/hannahsgr)
> - [ ] [Kimberly Tellez](https://github.com/hackforla/access-the-data/issues/assigned/kimberly-tellez)
> - [ ] [Sara Brady](https://github.com/hackforla/access-the-data/issues/assigned/bradyse)
> - [ ] [Steffie Kim](https://github.com/hackforla/access-the-data/issues/assigned/steffiekim)

> PMs
> - [ ] [Lucy Chang](https://github.com/hackforla/access-the-data/issues/assigned/lrchang2)
> - [ ] [aj price](https://github.com/hackforla/access-the-data/issues/assigned/mxajPrice)

**Comment by mxajPrice** [comment]
This agenda is no longer needed now that the Design and Research teams have separated.
