### ISSUE TITLE
Roadmap Milestone Labels 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#95]
### Overview
We need to apply the milestone and labels associated with our roadmap to all our issues so we can track project progress. 

### Action Items
- [ ] Define milestone objective, requirements and features in [milestone breakdown](https://docs.google.com/spreadsheets/u/2/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=1172277014) 
- [ ] Create milestones
- [ ] Apply milestones to all issues
- [ ] Create milestone feature labels 
- [ ] Apply milestone feature labels to all issues
- [ ] Note issues with too many milestone feature labels 

### Resources/Instructions
[milestone breakdown document](https://docs.google.com/spreadsheets/u/2/d/1_cx15yObwAl3KZYJjDgqjXd7Njw2D05BfcSc1eGZDtU/edit#gid=1172277014)

**Comment by lrchang2** [comment]
finished first pass through milestones, need to go through old issues and make sure correct milestone is applied. next is to finish making feature labels and apply them

**Comment by lrchang2** [comment]
had sarah move her issues to the correct milestone

**Comment by lrchang2** [comment]
Please add update using this template (even if you have a pull request)

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures: "Add any pictures of the visual changes made to the site so far."

If you need help, be sure to either: 

1. ask for help at your next meeting
2. put a "Status: Help Wanted" label on your issue and pull request
3. put up a request for assistance on the #access-the-data channel.
